### ISSUE TITLE
MEAN.JS on PostgreSQL/Sequelize

### ISSUE THREAD

**Issue by mg1075** [mjhea0/node-postgres-sequelize#1]
Hello, 

Apologies, because this is not an "issue" per se and maybe is better suited as a comment on your blog.
I've been searching for PostgreSQL/Sequelize implementations for a while, and just found a project that takes the MEAN.JS boilerplate (meanjs.org) and replace Mongo and Mongoose with PostgreSQL and Sequelize. Lots of built-in goodness from all the work put into the MEAN.JS boilerplate, but instead using PostgreSQL. You might want to check it out!

https://github.com/StetSolutions/pean
https://github.com/meanjs/mean

**Comment by mjhea0** [comment]
Thanks. In the future, just add this as a comment on the blog itself.
